<div class="page-title">
  <div class="title_left">
    <h2>Cadastro de clientes</h2>
    <?php
    if (isset($view_empresa)) {
      $empresa = Company::find_by_id($view_empresa);
      echo '<p style="margin:0">'.$empresa->cnpj.'</p>';
      echo '<h3 style="margin:0">'.$empresa->empresa.'</h3>';
    }
    ?>
  </div>
</div>
<div class="clearfix"></div>
<div class="panel-body">
  <?php
  if (isset($view_cliente)) {
    $btn = 'Editar Cliente';
    $action = BASE . 'cliente/editar/'.$view_cliente->id;
    $values = [
      'cpf' => $view_cliente->cpf,
      'nome' => $view_cliente->nome,
      'email' => $view_cliente->email,
      'endereco' => $view_cliente->endereco,
      'celular' => $view_cliente->celular,
      'telefone' => $view_cliente->telefone,
      'recado' => $view_cliente->recado,
      'obs' => $view_cliente->obs,
      'idUserCliente' => $view_idCliente,
      'companies_id' => $view_cliente->companies_id
    ];
  }else{
    $btn = 'Cadastrar Cliente';
    $action = BASE . 'cliente/cadastrar/';
    $values = [
      'cpf' => $this->request->post('cpf'),
      'nome' => $this->request->post('nome'),
      'email' => $this->request->post('email'),
      'endereco' => $this->request->post('endereco'),
      'celular' => $this->request->post('celular'),
      'telefone' => $this->request->post('telefone'),
      'recado' => $this->request->post('recado'),
      'obs' => $this->request->post('obs'),
      'companies_id' => $this->request->post('companies_id')
    ];
  }
  Form::open('cadastrarcliente', $values, [
    'action' => $action,
    'enctype' => 'multipart/form-data',
    'prevent' => [
      'focus'
    ]
  ]
);
?>
<div class="col-sm-6">
  <?php
  Form::Textbox(
    'CPF:',
    'cpf',
    array(
      'required' => 1
    )
  );
  Form::Textbox(
    'Nome:',
    'nome',
    array(
      'required' => 1
    )
  );
  Form::Email(
    'Email:',
    'email',
    array(
      'required' => 1
    )
  );
  Form::Textarea(
    'Endereço:',
    'endereco',
    array(
      'required' => 1
    )
  );
  Form::Phone(
    'Celular:',
    'celular',
    array(
      'required' => 1
    )
  );
  Form::Phone(
    'Telefone:',
    'telefone'
  );
  Form::Phone(
    'Recado:',
    'recado'
  );
  ?>
</div>
<div class="col-sm-6">
  <?php
  Form::Textarea(
    'Obs:',
    'obs'
  );
  if (!isset($view_empresa)) {
    $empresas = Company::all();
    $options = array();
    foreach ($empresas as $empresa) {
      $options[$empresa->id] = $empresa->empresa;
    }
    Form::Select(
      "Empresa",
      "companies_id",
      $options,
      array(
        'required' => 1,
        'class' => 'selectpicker',
        'data-live-search' => 'true'
      )
    );
  }else{
    Form::Hidden(
      'companies_id',
      $view_empresa
    );
  }
  if (isset($view_cliente)) {
    $users = User::all();
    $option2 = array();
    foreach ($users as $value) {
      $option2[$value->id] = $value->name;
    }
    Form::Select(
      "Usuário",
      "idUserCliente",
      $option2
    );
  }
  Form::Button($btn, 'submit', [
    'style' => 'width: 80%;margin-top: 20px;float: right;',
    'class' => 'btn-success'
  ]);
  ?>
</div>
<?php
Form::close(false);
?>
</div>