<div class="panel-body">
	<div class="col-md-offset-10">
		<a href="<?php echo BASE.'empresa/cadastrar' ?>" class="btn btn-success">Cadastrar</a>
	</div>
	<table class="table">
		<thead>
			<tr>
				<th>CNPJ</th>
				<th>Empresa</th>
				<th>Contato</th>
				<th>Telefones</th>
				<th>Ações</th>
			</tr>
		</thead>
		<tbody>
			<?php
			if ($view_empresa){
				foreach ($view_empresa as $emp){
					?>
					<tr>
						<td><?php echo $emp->cnpj ?></td>
						<td><?php echo $emp->empresa ?></td>
						<td><?php echo $emp->contato ?></td>
						<td><?php
						if ($emp->telefone) {
							echo $emp->telefone;
						}
						if ($emp->celular) {
							echo "<br />".$emp->celular;
						}
						?></td>
						<td>
							<a href="<?php echo BASE.'divida/filtrar/'.$emp->id ?>" class="btn btn-info btn-sm">Dívidas</a>
							<a href="<?php echo BASE.'empresa/editar/'.$emp->id ?>" class="btn btn-warning btn-sm">Editar</a>
							<a href="<?php echo BASE.'empresa/excluir/'.$emp->id ?>" class="btn btn-danger btn-sm">Excluir</a>
						</td>
					</tr>
					<?php
				}
			}
			?>
		</tbody>
	</table>
</div>