<div class="row-fluid">
	<div class="page-title">
		<div class="title_left">
			<h2>Lista de Empresas</h2>
		</div>
	</div>
	<table class="table" id="tableFull">
		<thead>
			<tr>
				<th></th>
				<th>Empresa</th>
				<th>Documentos Faltantes</th>
				<th>Boletos Emitidos</th>
				<th>Boletos Pagos</th>
				<th>Clientes</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<?php
			if ($view_empresa){
				foreach ($view_empresa as $emp){
					$clientes = Client::busca_cliente($emp->id);
					$gerente = User::find_by_id($emp->gerente);
					$docs = Document::find(array('conditions' => array('companies_id = ?', $emp->id)));
					if (isset($gerente->cor)) {
						$bg = $gerente->cor;
					}else{
						$bg = '#fff';
					}
					?>
					<tr>
						<td>
							<div class="corEmp" style="background: <?php echo $bg ?>"></div>
						</td>
						<td>
							<small><?php echo $emp->cnpj ?></small>
							<p><?php echo $emp->empresa ?></p>
						</td>
						<td><?php if ($docs) { echo '<ul class="list-group docs">'.Document::printDoc($docs).'</ul>'; } ?></td>
						<td>
							<?php
							$vlTotal = 0;
							foreach ($clientes as $cliente) {
								$pags = Payment::find('all', array('conditions' => array('cliente_id = ?', $cliente->id)));
								if (count($pags)>0) {
									foreach ($pags as $pag) {
										$vlTotal += $pag->valor;
									}
								}
							}
							echo 'R$ '.number_format($vlTotal, 2, ",", ".");
							?>
						</td>
						<td>
							<?php
							$vlTotal = 0;
							foreach ($clientes as $cliente) {
								$pags = Payment::find('all', array('conditions' => array('cliente_id = ? AND status = "RECEIVED"', $cliente->id)));
								if (count($pags)>0) {
									foreach ($pags as $pag) {
										$vlTotal += $pag->valor;
									}
								}
							}
							echo 'R$ '.number_format($vlTotal, 2, ",", ".");
							?>
						</td>
						<td>
							<?php echo count($clientes); ?>
						</td>
						<td>
							<a href="<?php echo BASE.'cliente/empresa/'.$emp->id ?>" class="btn btn-info btn-sm">Clientes</a>
							<?php
							if ($this->auth->getUserRole() == 'administrator') {
								?>
								<a href="<?php echo BASE.'empresa/editar/'.$emp->id ?>" class="btn btn-warning btn-sm">Editar</a>
								<!--<a href="<?php echo BASE.'empresa/excluir/'.$emp->id ?>" class="btn btn-danger btn-sm">Excluir</a>-->
								<?php
							}
							?>
						</td>
					</tr>
					<?php
				}
			}
			?>
		</tbody>
	</table>
</div>

<!-- FastClick -->
<script src="<?php echo BOWER; ?>vendors/fastclick/lib/fastclick.js"></script>
<!-- NProgress -->
<script src="<?php echo BOWER; ?>vendors/nprogress/nprogress.js"></script>
<!-- Chart.js -->
<script src="<?php echo BOWER; ?>vendors/Chart.js/dist/Chart.min.js"></script>
<!-- gauge.js -->
<script src="<?php echo BOWER; ?>vendors/gauge.js/dist/gauge.min.js"></script>
<!-- bootstrap-progressbar -->
<script src="<?php echo BOWER; ?>vendors/bootstrap-progressbar/bootstrap-progressbar.min.js"></script>
<!-- iCheck -->
<script src="<?php echo BOWER; ?>vendors/iCheck/icheck.min.js"></script>
<!-- Skycons -->
<script src="<?php echo BOWER; ?>vendors/skycons/skycons.js"></script>
<!-- Flot -->
<script src="<?php echo BOWER; ?>vendors/Flot/jquery.flot.js"></script>
<script src="<?php echo BOWER; ?>vendors/Flot/jquery.flot.pie.js"></script>
<script src="<?php echo BOWER; ?>vendors/Flot/jquery.flot.time.js"></script>
<script src="<?php echo BOWER; ?>vendors/Flot/jquery.flot.stack.js"></script>
<script src="<?php echo BOWER; ?>vendors/Flot/jquery.flot.resize.js"></script>
<!-- Flot plugins -->
<script src="<?php echo BOWER; ?>vendors/flot.orderbars/js/jquery.flot.orderBars.js"></script>
<script src="<?php echo BOWER; ?>vendors/flot-spline/js/jquery.flot.spline.min.js"></script>
<script src="<?php echo BOWER; ?>vendors/flot.curvedlines/curvedLines.js"></script>
<!-- DateJS -->
<script src="<?php echo BOWER; ?>vendors/DateJS/build/date.js"></script>
<!-- JQVMap -->
<script src="<?php echo BOWER; ?>vendors/jqvmap/dist/jquery.vmap.js"></script>
<script src="<?php echo BOWER; ?>vendors/jqvmap/dist/maps/jquery.vmap.world.js"></script>
<script src="<?php echo BOWER; ?>vendors/jqvmap/examples/js/jquery.vmap.sampledata.js"></script>
<!-- bootstrap-daterangepicker -->
<script src="<?php echo BOWER; ?>vendors/moment/min/moment.min.js"></script>
<script src="<?php echo BOWER; ?>vendors/bootstrap-daterangepicker/daterangepicker.js"></script>