<div class="panel-body">
  <?php
  if (isset($view_divida)) {
    $action = BASE . 'divida/editar/'.$view_divida->id;
    $values = [
      'cpf' => $view_divida->cpf,
      'empresa' => $view_divida->empresa,
      'nome' => $view_divida->nome,
      'endereco' => $view_divida->endereco,
      'celular' => $view_divida->celular,
      'telefone' => $view_divida->telefone,
      'recado' => $view_divida->recado,
      'valor' => $view_divida->valor,
      'vencimento' => date('Y-m-d', strtotime($view_divida->vencimento)),
      'status' => $view_divida->status,
      'obs' => $view_divida->obs
    ];
  }else{
    $action = BASE . 'divida/cadastrar/';
    $values = [
      'cpf' => $this->request->post('cpf'),
      'empresa' => $this->request->post('empresa'),
      'nome' => $this->request->post('nome'),
      'endereco' => $this->request->post('endereco'),
      'celular' => $this->request->post('celular'),
      'telefone' => $this->request->post('telefone'),
      'recado' => $this->request->post('recado'),
      'valor' => $this->request->post('valor'),
      'vencimento' => $this->request->post('vencimento'),
      'status' => $this->request->post('status'),
      'obs' => $this->request->post('obs')
    ];
  }
  Form::open('cadastrardivida', $values, [
    'action' => $action,
    'enctype' => 'multipart/form-data',
    'prevent' => [
      'focus'
    ]
  ]);
  ?>
  <div class="col-sm-6">
    <?php
    Form::Textbox(
      'Cpf:',
      'cpf',
      array(
        'required' => 1
      )
    );
    Form::Select(
      "Empresa",
      "empresa",
      $view_option,
      $attributes = null
    );
    Form::Textbox(
      'Nome:',
      'nome',
      array(
        'required' => 1
      )
    );
    Form::Number(
      'Valor:',
      'valor',
      array(
        'required' => 1,
        'min' => 0,
        'step' => '.01'
      )
    );
    Form::Date(
      'Vencimento:',
      'vencimento',
      array(
        'required' => 1
      )
    );
    $status = State::busca(1);
    $options = array();
    if (count($status) < 1) {
      $options[0] = 'Nenhum status informado, contate o admin';
    }else{
      foreach ($status as $stat) {
        $options[$stat->id] = $stat->nome;
      }
    }
    Form::Select(
      "Status",
      "status",
      $options,
      array(
        'required' => 1
      )
    );
    Form::Textarea(
      'Endereço:',
      'endereco'
    );
    ?>
  </div>
  <div class="col-sm-6">
    <?php
    Form::Textbox(
      'Celular:',
      'celular'
    );
    Form::Textbox(
      'Telefone:',
      'telefone'
    );
    Form::Textbox(
      'Recado:',
      'recado'
    );
    Form::Textarea(
      'Observações:',
      'obs'
    );
    Form::Button('Cadastrar Dívida', 'submit', [
      'style' => 'width: 80%;float:  right;margin-top: 45px;',
      'class' => 'btn-success'
    ]);
    ?>
  </div>
  <?php
  Form::close(false);
  ?>
</div>