<div class="panel-body">
	<div class="row">
		<div class="col-md-10">
			<?php
			$empresa = Company::find_by_id($view_dividas[0]->empresa);
			?>
			<h4 style="margin-top: 7px;margin-bottom: 20px;">
				Dívidas da empresa: <?php echo $empresa->empresa ?>
			</h4>
		</div>
		<div class="col-md-2" style="text-align: center;">
			<a href="<?php echo BASE.'divida/cadastrar' ?>" class="btn btn-success">Cadastrar</a>
		</div>
	</div>
	<table class="table">
		<thead>
			<tr>
				<th>CPF</th>
				<th>Nome</th>
				<th>Valor Original</th>
				<th>Valor Atualizado</th>
				<th>Dívida desde...</th>
				<th>Atend.</th>
				<th>Status</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<?php
			if ($view_dividas){
				foreach ($view_dividas as $divida){
					$empresa = Company::find_by_id($divida->empresa);
					$atds = Call::busca($divida->id);
					$vlAtualizado = DividaController::vlAtualizado($divida->valor, $divida->vencimento, $empresa->multa, $empresa->juros);
					?>
					<tr>
						<td>
							<a href="<?php echo BASE.'divida/filtrarCpf/'.str_replace("/", "aa", $divida->cpf) ?>" class="btn btn-success">
								<?php echo $divida->cpf ?>
							</a>
						</td>
						<td><?php echo $divida->nome ?></td>
						<td>R$ <?php echo number_format($divida->valor, 2, ",", ".") ?></td>
						<td>R$ <?php echo $vlAtualizado; ?></td>
						<td style="text-align: center;"><?php echo date('d/m/Y', strtotime($divida->vencimento)) ?></td>
						<td style="text-align: center;"><?php echo count($atds); ?></td>
						<td><?php echo State::find_by_id($divida->status)->nome; ?></td>
						<td>
							<button type="button" class="btn btn-info btn-sm" data-toggle="modal" data-target="#modalAtd<?php echo $divida->id ?>">
								ATENDIMENTO
							</button>
							<?php
							if ($this->auth->getUserRole() == 'administrator') {
								?>
								<a href="<?php echo BASE.'divida/editar/'.$divida->id ?>" class="btn btn-warning btn-sm">Editar</a>
								<a href="<?php echo BASE.'divida/excluir/'.$divida->id ?>" class="btn btn-danger btn-sm">Excluir</a>
								<?php
							}
							?>

							<!-- Modal -->
							<div class="modal fade bd-example-modal-lg" id="modalAtd<?php echo $divida->id ?>" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
								<div class="modal-dialog modal-lg" role="document">
									<div class="modal-content">
										<div class="modal-header">
											<h3 class="modal-title" id="exampleModalLongTitle">
												<?php echo $divida->nome; ?> - <?php echo $divida->cpf; ?> - <?php echo date('d/m/Y', strtotime($divida->vencimento)); ?>
											</h3>
											<p class="modal-subtitulo">
												<?php echo 'Celular: '.$divida->celular; ?> - <?php echo 'Telefone: '.$divida->telefone; ?> - <?php echo 'Recado: '.$divida->recado; ?>
											</p>
											<button type="button" class="close" data-dismiss="modal" aria-label="Close">
												<span aria-hidden="true">&times;</span>
											</button>
										</div>
										<div class="modal-body">
											<table class="table">
												<thead>
													<th>Valor</th>
													<th>Atendimento</th>
													<th>Status</th>
													<th>Data</th>
												</thead>
												<tbody>
													<?php
													foreach ($atds as $atd) {
														?>
														<tr>
															<td>R$ <?php echo number_format($atd->vlneg, 2, ",", "."); ?></td>
															<td><?php echo $atd->obs; ?></td>
															<td><?php echo State::find_by_id($atd->status)->nome; ?></td>
															<td><?php echo date("d/m/Y H:m", strtotime($atd->data_cad)); ?></td>
														</tr>
														<?php
													}
													?>
												</tbody>
											</table>
										</div>
										<div class="modal-footer">
											<button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
										</div>
									</div>
								</div>
							</div>
						</td>
					</tr>
					<?php
				}
			}
			?>
		</tbody>
	</table>
</div>