<div class="panel-body">
	<div class="row">
		<div class="col-md-9">
			<?php
			if (isset($view_empresa) && !is_null($view_empresa)) {
				?>
				<h4 style="margin-top: 7px;margin-bottom: 20px;">
					Dívidas da empresa: <?php echo $view_empresa->empresa ?>
					(<?php echo $view_empresa->contato ?> - <?php echo $view_empresa->telefone ?>)
				</h4>
				<?php
			}
			?>
		</div>
		<div class="col-md-3" style="text-align: center;">
			<a href="<?php echo BASE.'divida/cadastrar' ?>" class="btn btn-success">Cadastrar</a>
		</div>
	</div>
	<table class="table">
		<thead>
			<tr>
				<th>CPF</th>
				<th>Empresa</th>
				<th>Nome</th>
				<th>Valor</th>
				<th>Status</th>
				<th>Ações</th>
			</tr>
		</thead>
		<tbody>
			<?php
			if ($view_dividas){
				foreach ($view_dividas as $divida){
					$empresa = Company::find_by_id($divida->empresa);
					?>
					<tr>
						<td><?php echo $divida->cpf ?></td>
						<td><?php echo $empresa->empresa; ?></td>
						<td><?php echo $divida->nome ?></td>
						<td>R$ <?php echo number_format($divida->valor, 2, ",", ".") ?></td>
						<td><?php echo State::find_by_id($divida->status)->nome; ?></td>
						<td>
							<button type="button" class="btn btn-info btn-sm" data-toggle="modal" data-target="#modalAtd<?php echo $divida->id ?>">
								Atd
							</button>
							<?php
							if ($this->auth->getUserRole() == 'administrator') {
								?>
								<a href="<?php echo BASE.'divida/editar/'.$divida->id ?>" class="btn btn-warning btn-sm">Editar</a>
								<a href="<?php echo BASE.'divida/excluir/'.$divida->id ?>" class="btn btn-danger btn-sm">Excluir</a>
								<?php
							}
							?>

							<!-- Modal -->
							<?php
							$atds = Call::busca($divida->id);
							?>
							<div class="modal fade bd-example-modal-lg" id="modalAtd<?php echo $divida->id ?>" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
								<div class="modal-dialog modal-lg" role="document">
									<div class="modal-content">
										<div class="modal-header">
											<h3 class="modal-title" id="exampleModalLongTitle">
												<?php echo $divida->nome; ?> - <?php echo $divida->cpf; ?> - <?php echo date('d/m/Y', strtotime($divida->vencimento)); ?>
											</h3>
											<p class="modal-subtitulo">
												<?php echo 'Celular: '.$divida->celular; ?> - <?php echo 'Telefone: '.$divida->telefone; ?> - <?php echo 'Recado: '.$divida->recado; ?>
											</p>
											<button type="button" class="close" data-dismiss="modal" aria-label="Close">
												<span aria-hidden="true">&times;</span>
											</button>
										</div>
										<div class="modal-body">
											<?php
											$action = BASE . 'divida/cadLog/'.$divida->id.'/'.$divida->empresa;
											$values = [
												'vlNegociado' => $this->request->post('vlNegociado'),
												'obs' => $this->request->post('obs'),
												'status' => $this->request->post('status')
											];
											Form::open('cadLog'.$divida->id, $values, [
												'action' => $action,
												'view' => "Vertical",
												'enctype' => 'multipart/form-data',
												'prevent' => [
													'focus'
												]
											]);
											?>
											<div class="col-md-6">
												<?php
												Form::Number(
													'Valor da Negociação:',
													'vlNeg',
													array(
														'value' => $divida->valor,
														'required' => 1
													)
												);
												$status = State::busca(2);
												$options = array();
												if (count($status) < 1) {
													$options[0] = 'Nenhum status informado, contate o admin';
												}else{
													foreach ($status as $stat) {
														$options[$stat->id] = $stat->nome;
													}
												}
												Form::Select(
													"Status",
													"status",
													$options,
													array(
														'required' => 1
													)
												);
												Form::Button('Cadastrar Atd', 'submit', [
													'style' => 'width: 100%',
													'class' => 'btn-success'
												]);
												?>
											</div>
											<div class="col-md-6">
												<?php
												Form::Textarea(
													'Atendimento:',
													'obs',
													array(
														'required' => 1,
														'rows' => 6
													)
												);
												?>
											</div>
											<?php
											Form::close(false);
											?>
											<table class="table">
												<thead>
													<th>Valor</th>
													<th>Atendimento</th>
													<th>Status</th>
													<th>Data</th>
												</thead>
												<tbody>
													<?php
													foreach ($atds as $atd) {
														?>
														<tr>
															<td>R$ <?php echo number_format($atd->vlneg, 2, ",", "."); ?></td>
															<td><?php echo $atd->obs; ?></td>
															<td><?php echo State::find_by_id($atd->status)->nome; ?></td>
															<td><?php echo date("Y-m-d H:m", strtotime($atd->data_cad)); ?></td>
														</tr>
														<?php
													}
													?>
												</tbody>
											</table>
										</div>
										<div class="modal-footer">
											<button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
										</div>
									</div>
								</div>
							</div>
						</td>
					</tr>
					<?php
				}
			}
			?>
		</tbody>
	</table>
</div>