<div class="panel-body">
	<div class="row">
		<div class="col-md-10">
			<?php
			if (isset($view_empresa) && !is_null($view_empresa)) {
				?>
				<h4 style="margin-top: 7px;margin-bottom: 20px;">
					Dívidas da empresa: <?php echo $view_empresa->empresa ?>
					(<?php echo $view_empresa->contato ?> - <?php echo $view_empresa->telefone ?>)
				</h4>
				<?php
			}
			?>
		</div>
		<div class="col-md-2" style="text-align: center;">
			<a href="<?php echo BASE.'divida/cadastrar' ?>" class="btn btn-success">Cadastrar</a>
		</div>
	</div>
	<table class="table">
		<thead>
			<tr>
				<th>CPF</th>
				<th>Empresa</th>
				<th>Nome</th>
				<th>Contato</th>
				<th>Valor Original</th>
				<th>Valor Atualizado</th>
				<th>Dívida desde...</th>
				<th>Status</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<?php
			if ($view_dividas){
				foreach ($view_dividas as $divida){
					$empresa = Company::find_by_id($divida->empresa);
					$vlAtualizado = DividaController::vlAtualizado($divida->valor, $divida->vencimento, $empresa->multa, $empresa->juros);
					?>
					<tr>
						<td>
							<a href="<?php echo BASE.'divida/filtrarCpf/'.str_replace("/", "aa", $divida->cpf) ?>" class="btn btn-success">
								<?php echo $divida->cpf ?>
							</a>
						</td>
						<td><?php echo $empresa->empresa; ?></td>
						<td><?php echo $divida->nome ?></td>
						<td>
							<?php
							echo $divida->celular;
							if ($divida->telefone != "") {
								echo "<br />".$divida->telefone;
							}
							if ($divida->recado != "") {
								echo "<br />".$divida->recado;
							}
							?>
						</td>
						<td>R$ <?php echo number_format($divida->valor, 2, ",", ".") ?></td>
						<td>R$ <?php echo $vlAtualizado; ?></td>
						<td style="text-align: center;"><?php echo date('d/m/Y', strtotime($divida->vencimento)) ?></td>
						<td><?php echo State::find_by_id($divida->status)->nome; ?></td>
						<td>
							<?php
							if ($this->auth->getUserRole() == 'administrator') {
								?>
								<a href="<?php echo BASE.'divida/editar/'.$divida->id ?>" class="btn btn-warning btn-sm">Editar</a>
								<a href="<?php echo BASE.'divida/excluir/'.$divida->id ?>" class="btn btn-danger btn-sm">Excluir</a>
								<?php
							}
							?>
						</td>
					</tr>
					<?php
				}
			}
			?>
		</tbody>
	</table>
</div>