</div>
</div>
</div>
</div>
<div class="container">
	<div class="row">
		<div class="col-md-4 col-md-offset-4 text-center">
			<a href="https://www.websampa.com.br/?ref=123" target="_blank" title="WebSampa Publicidades &amp; Sistemas Web">
				<img src="https://websampa.com.br/images/banners/copy.php/?ref=123" alt="Copy Websampa">
			</a>
		</div>
	</div>
</div>
<script type="text/javascript" src="<?php echo BOWER ?>bootstrap/dist/js/bootstrap.min.js"></script>
</body>
</html>