<!doctype html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta name="author" content="Wesley Teixeira - wesleyteixeira.com.br">
    <meta name="generator" content="DivCred">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?php echo $view_title; ?></title>
    <link rel="shortcut icon" href="<?php echo IMG; ?>favicon.jpg" type="image/x-icon">
    <link rel="stylesheet" href="<?php echo BOWER; ?>bootstrap/dist/css/bootstrap.min.css" type="text/css">
    <link rel="stylesheet" href="<?php echo BOWER; ?>font-awesome/css/font-awesome.min.css" type="text/css">
    <link rel="stylesheet" href="<?php echo CSS; ?>main.css" type="text/css">
    <script type="text/javascript" src="<?php echo BOWER ?>jquery/dist/jquery.min.js"></script>
    <?php
    echo $add_css;
    echo $add_js;
    ?>
</head>
<body>
    <div class="container">
        <div class="row">
          <div class="col-md-6 col-md-offset-3">
            <div class="panel panel-custom">
              <div class="panel-heading">
                <a id="logo" href="<?php echo BASE; ?>">
                  <img class="img-responsive" src="<?php echo IMG; ?>logo_divcred.png" alt="">
              </a> <br>
              <?php echo (isset($this->menu) ? $this->menu : ''); ?>
              <?php echo(isset($this->alert)?$this->alert:''); ?>
          </div>